name: my first workflow
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  jobname1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world"
        shell: bash
  jobname2:
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: echo "Hello world in job2"