name: Terraform deployment
on:
  push:
    branches: main
jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: dev env
        run: echo "This is environment ${{ vars.ENV }}"
        shell: bash
  
  STG:
    runs-on: ubuntu-latest
    environment: stg
    needs: DEV
    steps:
      - uses: actions/checkout@v2
      - name: qa env
        run: echo "This is environment test ${{ vars.ENV }}"
        shell: bash
