name: my first workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default: Welcome
  push:
    branches: main
jobs:
  jobname1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world ${{ inputs.name }}"
        shell: bash
  jobname2:
    runs-on: ubuntu-latest
    steps:
      - name: Second job
        run: echo "Hello world in job2"
