name: thrid_workflow

on:
  push:
    branches: main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: 'false'
      version:
        description: 'Application version'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Debug Mode: ${{ github.event.inputs.debug_mode }}"
          echo "Version: ${{ github.event.inputs.version }}"

      - name: Deploy
        run: |
          # Your deployment logic here
          echo "Deploying to ${{ github.event.inputs.environment }}"
